### ISSUE TITLE
Bug：当时速为6.4时显示错误界面

### ISSUE THREAD

**Issue by codingswag998** [esojourn/calc#1]
当使用mph=4 （kmh=6.4）时，第一次按按钮显示不管算，但此时马上按下按钮时就会显示正常结果。
第一次的定义为： 刷新页面或者按下reset按钮
之后再按按钮都会显示正常结果
在网页浏览器测试的

截图： https://drive.google.com/file/d/1QJDqxNDsY5nX5r6NhsuENjuozwIgk2-V/view?usp=sharing

**Comment by esojourn** [comment]
谢谢回复和截图。不过您的本身，配速是400吧？倒是可以加个功能，写成4、5、6的时候，自动转成400、500.
